import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { api } from '../services/api';
import { motion } from 'motion/react';
import { Loader2, AlertCircle, QrCode } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

export const QRResolverPage: React.FC = () => {
  const { qrId } = useParams<{ qrId: string }>();
  const navigate = useNavigate();
  const { user, isAuthReady } = useAuth();
  const [status, setStatus] = useState<'loading' | 'error' | 'unlinked'>('loading');
  const [message, setMessage] = useState('');

  useEffect(() => {
    const resolveQR = async () => {
      if (!qrId || !isAuthReady) return;

      console.log('Resolving QR:', qrId);
      try {
        const qrData = await api.getQRData(qrId);
        console.log('QR Data:', qrData);
        
        if (!qrData) {
          setStatus('error');
          setMessage('Invalid QR Code. This code was not generated by ToLetBro.');
          return;
        }

        if (qrData.status === 'UNLINKED') {
          console.log('QR is UNLINKED');
          // Check if user is logged in as owner
          if (user && user.role === 'OWNER') {
            navigate(`/link-qr/${qrId}`, { replace: true });
          } else {
            setStatus('unlinked');
          }
          return;
        }

        if (qrData.status === 'LINKED' && qrData.ownerId) {
          console.log('QR is LINKED to owner:', qrData.ownerId);
          const properties = await api.getPropertiesByOwnerId(qrData.ownerId);
          console.log('Found properties:', properties.length);
          
          if (properties.length === 1) {
            // Only one property, direct to details
            const p = properties[0];
            const slug = p.slug || p.title
              .toLowerCase()
              .replace(/[^a-z0-9]+/g, '-')
              .replace(/(^-|-$)/g, '');
            setMessage('Redirecting to property details...');
            navigate(`/property/${slug}-${p.id}`, { replace: true });
          } else {
            // Multiple properties or zero, show list
            navigate(`/owner-properties/${qrData.ownerId}`, { replace: true });
          }
        } else {
          console.log('QR is LINKED but ownerId is missing');
          setStatus('error');
          setMessage('This QR code is linked but owner information is missing.');
        }
      } catch (error) {
        console.error('QR Resolution Error:', error);
        setStatus('error');
        setMessage('An error occurred while resolving the QR code.');
      }
    };

    resolveQR();
  }, [qrId, navigate, user, isAuthReady]);

  if (status === 'loading') {
    return (
      <div className="flex h-[80vh] flex-col items-center justify-center text-center px-6">
        <motion.div
          animate={{ rotate: 360 }}
          transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
          className="mb-6 text-brand"
        >
          <Loader2 size={48} />
        </motion.div>
        <h2 className="text-2xl font-bold text-[var(--text-primary)]">{message || 'Resolving QR Code...'}</h2>
        <p className="mt-2 text-[var(--text-secondary)]">{message ? 'Just a moment while we take you there.' : 'Please wait while we find the property details.'}</p>
      </div>
    );
  }

  if (status === 'error') {
    return (
      <div className="flex h-[80vh] flex-col items-center justify-center text-center px-6">
        <div className="mb-6 flex h-20 w-20 items-center justify-center rounded-full bg-red-500/10 text-red-500">
          <AlertCircle size={40} />
        </div>
        <h2 className="text-2xl font-bold text-[var(--text-primary)]">Oops!</h2>
        <p className="mt-2 text-[var(--text-secondary)]">{message}</p>
        <button 
          onClick={() => navigate('/')}
          className="mt-8 rounded-2xl bg-brand px-8 py-3 font-bold text-black transition-transform hover:scale-105"
        >
          Go Back Home
        </button>
      </div>
    );
  }

  if (status === 'unlinked') {
    return (
      <div className="flex h-[80vh] flex-col items-center justify-center text-center px-6">
        <div className="mb-6 flex h-20 w-20 items-center justify-center rounded-full bg-brand/10 text-brand">
          <QrCode size={40} />
        </div>
        <h2 className="text-2xl font-bold text-[var(--text-primary)]">Board Not Activated</h2>
        <p className="mt-2 text-[var(--text-secondary)] max-w-xs">
          This board is not yet activated by the owner. Are you the owner?
        </p>
        
        <div className="mt-12 space-y-4 w-full max-w-xs">
          <p className="text-xs font-bold uppercase tracking-widest text-[var(--text-secondary)] opacity-50">Are you the owner?</p>
          <button 
            onClick={() => navigate(`/link-qr/${qrId}`)}
            className="w-full rounded-2xl bg-brand py-4 font-bold text-black transition-transform hover:scale-105"
          >
            Login to Claim
          </button>
          <button 
            onClick={() => navigate('/')}
            className="w-full rounded-2xl border border-[var(--border)] py-4 font-bold text-[var(--text-primary)] transition-transform hover:scale-105"
          >
            Back to Home
          </button>
        </div>
      </div>
    );
  }

  return null;
};
